### ISSUE TITLE
Exceptions handle in PubSub

### ISSUE THREAD

**Issue by bitnoize** [mojolicious/mojo-pg#58]
* Mojo::Pg version: 4.14
* Perl version: 5.24.1
* Operating system: Linux Debian 9

### Steps to reproduce the behavior

use Mojo::Base -strict;
use Mojo::Pg;

my $pg = Mojo::Pg->new("postgresql://localhost/test");
my $pubsub = $pg->pubsub;

$pubsub->listen(test => sub {
  my ($pubsub, $payload) = @_;

  say $payload; # message received in any case
  die "Shit happens"; # exception happens only with $pubsub->notify
});

#### Without this command, die exception from listen callback not happens
$pubsub->notify(test => "test");

Mojo::IOLoop->start;

### Expected behavior
Die exception happens in any case, even if message send via NOTIFY test, 'test' from psql console

### Actual behavior
Die exception happens only if script sends self message via $pubsub->notify

Seems this is a bug.

**Comment by kraih** [comment]
Yes, that's a bug. We have to do an `eval` internally at a certain point because `$dbh->pg_notifies` will fail sometimes. That can probably be handled better.

**Comment by kraih** [comment]
[This line](https://github.com/mojolicious/mojo-pg/blob/581995ce510ca56f5e0876ef0e051f24d0b7a024/lib/Mojo/Pg/Database.pm#L162) is eating the exception.
