### ISSUE TITLE
No primary key on `mojo_migrations` table

### ISSUE THREAD

**Issue by veryrusty** [mojolicious/mojo-pg#65]
* Mojo::Pg version: 4.17

When migrating a postgres database for an app that uses Minion between postgres clusters (using `pg_logical`), the process stops as there is no primary key on the `mojo_migrations` table.  While a pg_dump/pg_restore approach would work, the (streaming) logical replication approach reduces downtime/outages involved.

The `mojo_migrations` table has a unique constraint on its `name` column; as such, its a candidate (or alternate) key for the table. Could this be declared as a primary key instead.

**Comment by kraih** [comment]
That would seem reasonable.

**Comment by kraih** [comment]
Fixed in 4.17.

**Comment by veryrusty** [comment]
Thanks @kraih !
