### ISSUE TITLE
CRUD statements have placeholders instead of actual values

### ISSUE THREAD

**Issue by crlmahlberg** [mojolicious/mojo-pg#66]
* Mojo::Pg version: **4.17**
* Perl version: **5.28.1**
* Operating system: **Ubuntu 19.10**

### Steps to reproduce the behavior
_My Perl script has the following lines in it:_

`my $insert_query = $pg->abstract->insert(
    'my_table',
    {   city => 'New York',
        id   => 1000
    }
);`

`my $update_query = $pg->abstract->update(
    'my_table',
    { city => "Los Angeles" },
    { id   => 1000 }
);`

`print Dumper $insert_query;`
`print Dumper $update_query;`

### Expected behavior
_What I would expect the command line output to be, having read the Mojo::Pg documentation and looked at the official exemples:_

`$VAR1 = 'INSERT INTO "my_table" ( "city", "id") VALUES ( "New York", 1000 )';`
`$VAR1 = 'UPDATE "my_table" SET "city" = "Los Angeles" WHERE ( "id" = 1000 )';`

### Actual behavior
_What I actually received is a string with placeholders instead of actual values. What good are the values entered into the insert and update functions, if they are not being used?_

`$VAR1 = 'INSERT INTO "my_table" ( "city", "id") VALUES ( ?, ? )';`
`$VAR1 = 'UPDATE "my_table" SET "city" = ? WHERE ( "id" = ? )';`

_I might be overlooking something. Thanks for your help!_

**Comment by Grinnz** [comment]
This is how SQL::Abstract works. Those methods return a list, and the rest of the list is the placeholder values. With Mojo::Pg you should not normally need to do this directly, the $pg->db->insert and similar methods will do all of this for you and return a results object.

**Comment by shadowcat-mst** [comment]
Please see http://bobby-tables.com/ to learn what SQL injection is and why production quality code should always use placeholders.

(yours, one of the SQL::Abstract developers)

**Comment by Grinnz** [comment]
Please feel free to use the support channels (https://mojolicious.org/perldoc#SUPPORT) if you have any further questions.

**Comment by crlmahlberg** [comment]
Ok, thanks for the help.
