### ISSUE TITLE
Add migrations with multiple SQL files

### ISSUE THREAD

**Issue by kraih** [mojolicious/mojo-pg#71]
The single file approach can get messy very quick if you have too many migrations. There should probably be another option where it uses a directory with multiple SQL files.
```
migrations/1/up.sql
migrations/1/down.sql
migrations/2/up.sql
migrations/3/up.sql
migrations/3/down.sql
```
Maybe like that. We'll have to see what works best for keeping many migration steps around.

**Comment by jhthorsen** [comment]
This is resolved by #72
