### ISSUE TITLE
PubSub is calling non-existent Mojo::Util::_global_destruction

### ISSUE THREAD

**Issue by akarelas** [mojolicious/mojo-pg#75]
* Mojo::Pg version: 4.23
* Mojolicious version: 8.72
* Perl version: v5.32
* Operating system: Ubuntu 20.04

Mojo::Util 8.72 doesn't have a _global_destruction method anymore, so it seems wrong that [Mojo::Pg::Pubsub line 34](https://metacpan.org/release/Mojo-Pg/source/lib/Mojo/Pg/PubSub.pm#L34) calls it.

### Steps to reproduce the behavior
I tried to close my pubsub-using app, and got this error message:

```
	(in cleanup) Undefined subroutine &Mojo::Util::_global_destruction called at /home/appuser/website-com/perl/local/lib/perl5/Mojo/Pg/PubSub.pm line 34 during global destruction.
```

### Expected behavior
I got an error message

### Actual behavior
I shouldn't have gotten an error message

**Comment by kraih** [comment]
Fixed long ago.
