### ISSUE TITLE
Documentation missing

### ISSUE THREAD

**Issue by PaulGWebster** [mojolicious/mojo-pg#82]
* Mojo::Pg version: Latest
* Perl version: 5.28.0
* Operating system: FreeBSD 13.0-Stable

### Steps to reproduce the behavior
Documentation problem

### Expected behavior
Clear documenatation

### Actual behavior

new() call is not described in documentation, so does not state what the pg => $pg is (or the dbh for that matter)

**Comment by kraih** [comment]
Please use the forum for support requests. https://docs.mojolicious.org/#SUPPORT

**Comment by PaulGWebster** [comment]
Seems a valid bug, had to go look in the t/ folder to find an example of what the heck pg => is and it does not say anywhere in the POD
